### ISSUE TITLE
Asp.net

### ISSUE THREAD

**Issue by ggmueller** [Code-Inside/KnowYourStack#4]

**Comment by robertmuehsig** [comment]
What repos would you suggest that fits for ASP.NET that is not related to aapnetcore?

**Comment by robertmuehsig** [comment]
Would those fit for you:
https://github.com/aspnet/AspNetWebStack
https://github.com/aspnet/AspNetWebOptimization
https://github.com/aspnet/AspNetKatana

Please add any other asp.net related repo here and I will do the rest 👍

**Comment by ggmueller** [comment]
Hi, sorry opening it was a mistake on my side.

**Comment by robertmuehsig** [comment]
Well - I could add the "classic" asp.net stuff, but would like get the right naming to reduce any confusing with the current ASP.NET Core development... or is this not worth it?

**Comment by ggmueller** [comment]
Well there sure is interest in classic asp.net stuff out there.
For example, if you are looking at the comments here: https://blogs.msdn.microsoft.com/dotnet/2017/09/13/net-framework-4-7-1-asp-net-and-configuration-features/
And I guess there will be huge interest in migration stuff coming from classic ASP.NET (even Webforms) to ASP.NET Core
